name: Release Github notes

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Specify the version for this release'
        type: string
      npm_package:
        required: true
        description: 'npm package of the release repo'
        type: string

permissions:
  contents: write

jobs:
  release:
    uses: cloudscape-design/.github/.github/workflows/release-gh-notes.yml@main
    secrets: inherit
    with:
      npm_package: ${{ github.event.inputs.npm_package }}
      version: ${{ github.event.inputs.version }}
